Repository alphagov/smart-answers, pull requests merged in 2018-05, with the labels that each got.

#3495 Flatten marriage abroad for Ethiopia flow to 18 outcomes
  lib/data/marriage_abroad_data.yml
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/ethiopia/_title.govspeak.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/ethiopia/ceremony_country/partner_british/_opposite_sex.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/ethiopia/ceremony_country/partner_british/_same_sex.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/ethiopia/ceremony_country/partner_local/_opposite_sex.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/ethiopia/ceremony_country/partner_local/_same_sex.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/ethiopia/ceremony_country/partner_other/_opposite_sex.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/ethiopia/ceremony_country/partner_other/_same_sex.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/ethiopia/third_country/partner_british/_opposite_sex.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/ethiopia/third_country/partner_british/_same_sex.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/ethiopia/third_country/partner_local/_opposite_sex.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/ethiopia/third_country/partner_local/_same_sex.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/ethiopia/third_country/partner_other/_opposite_sex.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/ethiopia/third_country/partner_other/_same_sex.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/ethiopia/uk/partner_british/_opposite_sex.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/ethiopia/uk/partner_british/_same_sex.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/ethiopia/uk/partner_local/_opposite_sex.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/ethiopia/uk/partner_local/_same_sex.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/ethiopia/uk/partner_other/_opposite_sex.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/ethiopia/uk/partner_other/_same_sex.erb
  test/artefacts/marriage-abroad/ethiopia/ceremony_country/partner_british/opposite_sex.txt
  test/artefacts/marriage-abroad/ethiopia/ceremony_country/partner_british/same_sex.txt
  test/artefacts/marriage-abroad/ethiopia/ceremony_country/partner_local/opposite_sex.txt
  test/artefacts/marriage-abroad/ethiopia/ceremony_country/partner_local/same_sex.txt
  test/artefacts/marriage-abroad/ethiopia/ceremony_country/partner_other/opposite_sex.txt
  test/artefacts/marriage-abroad/ethiopia/ceremony_country/partner_other/same_sex.txt
  test/artefacts/marriage-abroad/ethiopia/third_country/partner_british/opposite_sex.txt
  test/artefacts/marriage-abroad/ethiopia/third_country/partner_british/same_sex.txt
  test/artefacts/marriage-abroad/ethiopia/third_country/partner_local/opposite_sex.txt
  test/artefacts/marriage-abroad/ethiopia/third_country/partner_local/same_sex.txt
  test/artefacts/marriage-abroad/ethiopia/third_country/partner_other/opposite_sex.txt
  test/artefacts/marriage-abroad/ethiopia/third_country/partner_other/same_sex.txt
  test/artefacts/marriage-abroad/ethiopia/uk/partner_british/opposite_sex.txt
  test/artefacts/marriage-abroad/ethiopia/uk/partner_british/same_sex.txt
  test/artefacts/marriage-abroad/ethiopia/uk/partner_local/opposite_sex.txt
  test/artefacts/marriage-abroad/ethiopia/uk/partner_local/same_sex.txt
  test/artefacts/marriage-abroad/ethiopia/uk/partner_other/opposite_sex.txt
  test/artefacts/marriage-abroad/ethiopia/uk/partner_other/same_sex.txt
  test/data/marriage-abroad-files.yml
  test/data/marriage-abroad-responses-and-expected-results.yml
Labels: Passed content review

#3511 Update Lower Earning Limit for 2018
  lib/data/rates/maternity_paternity_adoption.yml
  lib/data/rates/maternity_paternity_birth.yml
  lib/data/rates/statutory_sick_pay.yml
  lib/smart_answer/calculators/pay_leave_for_parents_calculator.rb
  test/artefacts/pay-leave-for-parents/yes/2012-02-01/employee/employee/yes/yes.txt
  test/artefacts/pay-leave-for-parents/yes/2012-02-01/employee/employee/yes/yes/yes/yes/yes.txt
  test/data/calculate-statutory-sick-pay-files.yml
  test/data/maternity-paternity-calculator-files.yml
  test/data/pay-leave-for-parents-files.yml
  test/integration/smart_answer_flows/calculate_statutory_sick_pay_test.rb
  test/integration/smart_answer_flows/maternity_calculator_test.rb
  test/unit/calculators/pay_leave_for_parents_calculator_test.rb
Labels: Needs content review

#3510 Flatten Iceland into three outcomes, based on user location
  lib/data/marriage_abroad_data.yml
  lib/smart_answer/calculators/marriage_abroad_calculator.rb
  lib/smart_answer/calculators/marriage_abroad_data_query.rb
  lib/smart_answer_flows/marriage-abroad.rb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/finland/_ceremony_country.govspeak.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/finland/_third_country.govspeak.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/iceland/_ceremony_country.govspeak.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/iceland/_third_country.govspeak.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/iceland/_title.govspeak.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/iceland/_uk.govspeak.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/outcome_marriage_abroad_in_finland.govspeak.erb
  test/artefacts/marriage-abroad/iceland/ceremony_country.txt
  test/artefacts/marriage-abroad/iceland/ceremony_country/partner_british/opposite_sex.txt
  test/artefacts/marriage-abroad/iceland/ceremony_country/partner_british/same_sex.txt
  test/artefacts/marriage-abroad/iceland/ceremony_country/partner_local/opposite_sex.txt
  test/artefacts/marriage-abroad/iceland/ceremony_country/partner_local/same_sex.txt
  test/artefacts/marriage-abroad/iceland/ceremony_country/partner_other/opposite_sex.txt
  test/artefacts/marriage-abroad/iceland/ceremony_country/partner_other/same_sex.txt
  test/artefacts/marriage-abroad/iceland/third_country.txt
  test/artefacts/marriage-abroad/iceland/third_country/partner_british/opposite_sex.txt
  test/artefacts/marriage-abroad/iceland/third_country/partner_british/same_sex.txt
  test/artefacts/marriage-abroad/iceland/third_country/partner_local/opposite_sex.txt
  test/artefacts/marriage-abroad/iceland/third_country/partner_local/same_sex.txt
  test/artefacts/marriage-abroad/iceland/third_country/partner_other/opposite_sex.txt
  test/artefacts/marriage-abroad/iceland/third_country/partner_other/same_sex.txt
  test/artefacts/marriage-abroad/iceland/uk.txt
  test/artefacts/marriage-abroad/iceland/uk/partner_british/opposite_sex.txt
  test/artefacts/marriage-abroad/iceland/uk/partner_british/same_sex.txt
  test/artefacts/marriage-abroad/iceland/uk/partner_local/opposite_sex.txt
  test/artefacts/marriage-abroad/iceland/uk/partner_local/same_sex.txt
  test/artefacts/marriage-abroad/iceland/uk/partner_other/opposite_sex.txt
  test/artefacts/marriage-abroad/iceland/uk/partner_other/same_sex.txt
  test/data/marriage-abroad-files.yml
  test/data/marriage-abroad-responses-and-expected-results.yml
  test/integration/smart_answer_flows/marriage_abroad_test.rb
  test/unit/calculators/marriage_abroad_data_query_test.rb
  test/unit/marriage_abroad_outcome_flattener_test.rb
Labels: Waiting on content review

#3523 Flatten marriage abroad sa
  lib/data/marriage_abroad_data.yml
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/south-africa/_opposite_sex.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/south-africa/_same_sex.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/south-africa/_title.govspeak.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/south-africa/ceremony_country/partner_british/_opposite_sex.govspeak.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/south-africa/ceremony_country/partner_british/_same_sex.govspeak.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/south-africa/ceremony_country/partner_local/_opposite_sex.govspeak.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/south-africa/ceremony_country/partner_local/_same_sex.govspeak.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/south-africa/ceremony_country/partner_other/_opposite_sex.govspeak.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/south-africa/ceremony_country/partner_other/_same_sex.govspeak.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/south-africa/third_country/partner_british/_opposite_sex.govspeak.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/south-africa/third_country/partner_british/_same_sex.govspeak.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/south-africa/third_country/partner_local/_opposite_sex.govspeak.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/south-africa/third_country/partner_local/_same_sex.govspeak.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/south-africa/third_country/partner_other/_opposite_sex.govspeak.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/south-africa/third_country/partner_other/_same_sex.govspeak.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/south-africa/uk/partner_british/_opposite_sex.govspeak.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/south-africa/uk/partner_british/_same_sex.govspeak.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/south-africa/uk/partner_local/_opposite_sex.govspeak.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/south-africa/uk/partner_local/_same_sex.govspeak.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/south-africa/uk/partner_other/_opposite_sex.govspeak.erb
  lib/smart_answer_flows/marriage-abroad/outcomes/countries/south-africa/uk/partner_other/_same_sex.govspeak.erb
  test/artefacts/marriage-abroad/south-africa/ceremony_country/partner_british/opposite_sex.txt
  test/artefacts/marriage-abroad/south-africa/ceremony_country/partner_british/same_sex.txt
  test/artefacts/marriage-abroad/south-africa/ceremony_country/partner_local/opposite_sex.txt
  test/artefacts/marriage-abroad/south-africa/ceremony_country/partner_local/same_sex.txt
  test/artefacts/marriage-abroad/south-africa/ceremony_country/partner_other/opposite_sex.txt
  test/artefacts/marriage-abroad/south-africa/ceremony_country/partner_other/same_sex.txt
  test/artefacts/marriage-abroad/south-africa/opposite_sex.txt
  test/artefacts/marriage-abroad/south-africa/same_sex.txt
  test/artefacts/marriage-abroad/south-africa/third_country/partner_british/opposite_sex.txt
  test/artefacts/marriage-abroad/south-africa/third_country/partner_british/same_sex.txt
  test/artefacts/marriage-abroad/south-africa/third_country/partner_local/opposite_sex.txt
  test/artefacts/marriage-abroad/south-africa/third_country/partner_local/same_sex.txt
  test/artefacts/marriage-abroad/south-africa/third_country/partner_other/opposite_sex.txt
  test/artefacts/marriage-abroad/south-africa/third_country/partner_other/same_sex.txt
  test/artefacts/marriage-abroad/south-africa/uk/partner_british/opposite_sex.txt
  test/artefacts/marriage-abroad/south-africa/uk/partner_british/same_sex.txt
  test/artefacts/marriage-abroad/south-africa/uk/partner_local/opposite_sex.txt
  test/artefacts/marriage-abroad/south-africa/uk/partner_local/same_sex.txt
  test/artefacts/marriage-abroad/south-africa/uk/partner_other/opposite_sex.txt
  test/artefacts/marriage-abroad/south-africa/uk/partner_other/same_sex.txt
  test/data/marriage-abroad-files.yml
  test/data/marriage-abroad-responses-and-expected-results.yml
  test/integration/smart_answer_flows/marriage_abroad_test.rb
Labels: Needs content review
